# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci --verbose
      - env:
          APP_VERSION: ${{github.event.release.name}}
        run: npm run package
      # - env:
      #     WEB_EXT_API_KEY: ${{secrets.FIREFOX_USERNAME}}
      #     WEB_EXT_API_SECRET: ${{secrets.FIREFOX_PASSWORD}}
      #   run: npm run publish
      - name: GitHub Script - Upload assets for artifact
        uses: actions/github-script@v8
        with:
          script: |
            const { readFile, readdir } = await import('node:fs/promises');
            const { resolve : resolvePath } await import('node:path');
            
            const githubWorkspace = process.env.GITHUB_WORKSPACE;
            const directory = resolvePath(githubWorkspace, 'web-ext-artifacts');
            
            for (const fileName of await readdir(directory)) {
              const filePath = resolvePath(directory, fileName);
              const data = await readFile(filePath);
              github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: process.env.RELEASE_ID,
                name: fileName,
                data,
              });
            }
        env:
          RELEASE_ID: ${{github.event.release.id}}
          GITHUB_WORKSPACE: ${{github.workspace}}
